-- Extracted from D_INCOME.rep
-- Generated by AI extraction process
--------------------------------------------------------------------------------
-- Main Report Query (Q_1)
--------------------------------------------------------------------------------
SELECT TRUNC (i_date) m_date,
    visa,
    SUM (paid) paid,
    TO_NUMBER (TO_CHAR (i_date, 'd')) DAY
FROM installment i,
    reg r
WHERE r.reg_key = i.reg_key
    AND iscanceled = 2
    AND i_date >= :date_from
    AND i_date < :date_to + 1
    AND (
        i.created_by = :i_creator
        OR :i_creator IS NULL
    )
    AND (
        branch_code = :pbranch
        OR :pbranch IS NULL
    )
GROUP BY TRUNC (i_date),
    visa,
    TO_NUMBER (TO_CHAR (i_date, 'd'))
ORDER BY 1;
--------------------------------------------------------------------------------
-- Formula Columns (Reconstructed from binary strings)
--------------------------------------------------------------------------------
-- CF_BRANCHFORMULA
-- Retrieves branch name based on branch code parameter
/*
 FUNCTION CF_BRANCHFORMULA RETURN CHAR IS
 v_branch_name VARCHAR2(200);
 BEGIN
 IF :PBRANCH IS NOT NULL THEN
 SELECT BRANCH_NAME INTO v_branch_name 
 FROM BRANCHES  
 WHERE BRANCH_CODE = :PBRANCH;
 RETURN v_branch_name;
 END IF;
 RETURN NULL;
 END;
 */
-- Element: PAID_IN_VISAFORMULA
-- Calculates payment via VISA
/*
 FUNCTION PAID_IN_VISAFORMULA RETURN NUMBER IS
 BEGIN
 -- Logic inferred: If VISA flag is 1 (Active/True), return PAID amount.
 -- BUG FIX: Original code crashed for VISA=2 (default/null) or 3.
 -- We added a safe ELSE 0 to prevent ORA-06503.
 IF NVL(:VISA, 2) = 1 THEN
 RETURN :PAID;
 ELSE
 RETURN 0;
 END IF;
 END;
 */
-- Element: PAID_IN_CASHFORMULA
-- Calculates payment via CASH
/*
 FUNCTION PAID_IN_CASHFORMULA RETURN NUMBER IS
 BEGIN
 -- Logic inferred: If VISA flag is 1, return 0.
 -- BUG FIX: Original code crashed for VISA=2 (default/null) or 3.
 -- We added a safe ELSE :PAID to prevent ORA-06503.
 IF NVL(:VISA, 2) = 1 THEN
 RETURN 0;
 ELSE
 RETURN :PAID;
 END IF;
 END;
 */
-- Element: CF_DAYFORMULA
-- Decodes day number to day name
/*
 FUNCTION CF_DAYFORMULA RETURN CHAR IS
 BEGIN
 -- Logic inferred from partial string: "FUNCTION"CF_DAYFORMULA"RETURN"CHAR"DAY""="1" "ELSIF"2"
 IF :DAY = 1 THEN RETURN 'SUNDAY';
 ELSIF :DAY = 2 THEN RETURN 'MONDAY';
 ELSIF :DAY = 3 THEN RETURN 'TUESDAY';
 ELSIF :DAY = 4 THEN RETURN 'WEDNESDAY';
 ELSIF :DAY = 5 THEN RETURN 'THURSDAY';
 ELSIF :DAY = 6 THEN RETURN 'FRIDAY';
 ELSIF :DAY = 7 THEN RETURN 'SATURDAY';
 END IF;
 RETURN NULL;
 END;
 */