-- Extracted SQL from R_R_MODULE2
-- 1. Message Handling
SELECT DISPLAY_OPTION,
    DECODE(DISPLAY_LANG, 'E', E_DISPLAY_TEXT, 'A', DISPLAY_TEXT),
    DISPLAY_TYPE,
    SHOW_DEFAULT
FROM MESSAGES
WHERE MESS_CODE = :b1
    AND MESS_LEVEL = 'E'
    AND DB_CODE = :b2
    AND (
        DISPLAY_MODE = :b3
        OR DISPLAY_MODE = 'BOTH'
    );
SELECT SYSTEM_MESSAGES
FROM SYSTEM_TABLE_SEC;
SELECT DISPLAY_OPTION,
    DECODE(DISPLAY_LANG, 'E', E_DISPLAY_TEXT, 'A', DISPLAY_TEXT),
    DISPLAY_TYPE,
    SHOW_DEFAULT
FROM MESSAGES
WHERE MESS_CODE = :b1
    AND MESS_LEVEL = 'M'
    AND DB_CODE = :b2
    AND (
        DISPLAY_MODE = :b3
        OR DISPLAY_MODE = 'BOTH'
    );
-- 2. System and Object Security
SELECT DISPLAY_TITLE D
FROM SYSTEM_TABLE_SEC;
SELECT OBJECT_NAME N
FROM OBJECTS
WHERE UPPER(OBJECT_PATH) = UPPER(:b1);
SELECT OBJECT_ID
FROM OBJECTS
WHERE UPPER(OBJECT_PATH) = UPPER(:b1);
SELECT *
FROM USER_PRIVILEGE
WHERE USER_ID = :b1
    AND OBJECT_ID = :b2;
SELECT USER_GROUP
FROM USERS
WHERE USER_ID = :b1;
SELECT *
FROM GROUP_PRIVILEGE
WHERE GROUP_ID = :b1
    AND OBJECT_ID = :b2;
SELECT USE_RIGHTS R,
    USE_SECURITY S
FROM SYSTEM_TABLE_SEC;
-- 3. Temporary Tables Cleanup
DELETE FROM T_REG;
DELETE FROM T_REG_LINES;
DELETE FROM T_TESTS_ENTRY_LINES;
DELETE FROM T_TEXT_ENTRY_LINES;
DELETE FROM T_CULTURE_ENTRY_LINES;
-- 4. Registration Lines Processing
SELECT DISTINCT SEND_RESULT
FROM T_REG_LINES;
UPDATE T_REG_LINES L
SET TEST_STATUS = 3,
    RECEIVE_RESULT_USER = :b1,
    RECEIVE_DATE = SYSDATE;
SELECT COUNT(REG_KEY)
FROM T_REG;
SELECT COUNT(
        DISTINCT L.GROUP_CODE || L.TEST_CODE || L.TEST_TYPE
    )
FROM T_REG_LINES L;
SELECT DISTINCT BRANCH_NAME
FROM BRANCHES,
    REG_LINES L
WHERE BRANCH_CODE = L.SEND_TO_BRANCH;
-- 5. Tests Entry Lines
SELECT *
FROM T_TESTS_ENTRY_LINES;
SELECT COUNT(*)
FROM TESTS_ENTRY_LINES T
WHERE T.REG_KEY = :b1
    AND T.TEST_CODE = :b2
    AND T.GROUP_CODE = :b3
    AND T.TEST_TYPE = :b4;
UPDATE TESTS_ENTRY_LINES
SET RESULT = :b1,
    RESULT2 = :b2,
    DESCRIPTIVE = :b3,
    COMMENTS = :b4,
    R_FROM = :b5,
    R_TO = :b6,
    VERIFIED = :b7,
    VERIFIED_BY = :b8,
    UNIT = :b9,
    PROFILE_SER = :b10,
    TEST_STATUS = :b11,
    REPORT_PRINTED = :b12,
    VISIBLE = :b13,
    AGE_COMMENTS = :b14
WHERE REG_KEY = :b15
    AND TEST_CODE = :b16
    AND GROUP_CODE = :b17
    AND TEST_TYPE = :b18;
INSERT INTO TESTS_ENTRY_LINES
SELECT *
FROM T_TESTS_ENTRY_LINES T
WHERE T.REG_KEY = :b1
    AND T.TEST_CODE = :b2
    AND T.GROUP_CODE = :b3
    AND T.TEST_TYPE = :b4;
UPDATE REG_LINES L
SET TEST_STATUS = 3,
    SEND_RESULT = :b1,
    RECEIVE_RESULT_USER = :b2,
    RECEIVE_DATE = SYSDATE
WHERE (
        L.REG_KEY,
        L.GROUP_CODE,
        L.TEST_CODE,
        L.TEST_TYPE
    ) IN (
        SELECT T.REG_KEY,
            T.GROUP_CODE,
            T.REG_TEST_CODE,
            T.TEST_TYPE
        FROM T_TESTS_ENTRY_LINES T
    );
-- 6. Text Entry Lines Processing
DELETE FROM TEXT_ENTRY_LINES T
WHERE (T.REG_KEY, T.GROUP_CODE, TEST_CODE, T.TEST_TYPE) IN (
        SELECT L.REG_KEY,
            L.GROUP_CODE,
            L.TEST_CODE,
            L.TEST_TYPE
        FROM T_TEXT_ENTRY_LINES L
    );
INSERT INTO TEXT_ENTRY_LINES
SELECT *
FROM T_TEXT_ENTRY_LINES;
UPDATE REG_LINES L
SET TEST_STATUS = 3,
    RECEIVE_RESULT_USER = :b1,
    RECEIVE_DATE = SYSDATE
WHERE (
        L.REG_KEY,
        L.GROUP_CODE,
        L.TEST_CODE,
        L.TEST_TYPE
    ) IN (
        SELECT T.REG_KEY,
            T.GROUP_CODE,
            T.REG_TEST_CODE,
            T.TEST_TYPE
        FROM T_TEXT_ENTRY_LINES T
    );
-- 7. Culture Entry Lines Processing
DELETE FROM CULTURE_ENTRY_LINES T
WHERE (
        T.REG_KEY,
        T.GROUP_CODE,
        T.CULTURE_CODE,
        T.TEST_TYPE,
        T.ORG_CODE,
        T.ANTI_CODE,
        T.SENSTIVITY_CODE
    ) IN (
        SELECT L.REG_KEY,
            L.GROUP_CODE,
            L.CULTURE_CODE,
            L.TEST_TYPE,
            L.ORG_CODE,
            L.ANTI_CODE,
            L.SENSTIVITY_CODE
        FROM T_CULTURE_ENTRY_LINES L
    );
INSERT INTO CULTURE_ENTRY_LINES
SELECT *
FROM T_CULTURE_ENTRY_LINES T;
UPDATE REG_LINES L
SET TEST_STATUS = 3,
    RECEIVE_RESULT_USER = :b1,
    RECEIVE_DATE = SYSDATE
WHERE (
        L.REG_KEY,
        L.GROUP_CODE,
        L.TEST_CODE,
        L.TEST_TYPE
    ) IN (
        SELECT T.REG_KEY,
            T.GROUP_CODE,
            T.REG_TEST_CODE,
            T.TEST_TYPE
        FROM T_CULTURE_ENTRY_LINES T
    );