-- Extracted SQL from r_s module
-- 1. Message Retrieval
SELECT DISPLAY_OPTION,
    DECODE(
        DISPLAY_LANG,
        'E',
        E_DISPLAY_TEXT,
        'A',
        DISPLAY_TEXT
    ),
    DISPLAY_TYPE,
    SHOW_DEFAULT
FROM MESSAGES
WHERE MESS_CODE = :b1
    AND MESS_LEVEL = 'M'
    AND DB_CODE = :b2
    AND (
        DISPLAY_MODE = :b3
        OR DISPLAY_MODE = 'BOTH'
    );
-- 2. System Messages
SELECT SYSTEM_MESSAGES
FROM SYSTEM_TABLE_SEC;
-- 3. Display Title
SELECT DISPLAY_TITLE D
FROM SYSTEM_TABLE_SEC;
-- 4. Object Name Lookup
SELECT OBJECT_NAME N
FROM OBJECTS
WHERE UPPER(OBJECT_PATH) = UPPER(:b1);
-- 5. Object ID Lookup
SELECT OBJECT_ID
FROM OBJECTS
WHERE UPPER(OBJECT_PATH) = UPPER(:b1);
-- 6. User Privilege Check
SELECT *
FROM USER_PRIVILEGE
WHERE USER_ID = :b1
    AND OBJECT_ID = :b2;
-- 7. User Group Retrieval
SELECT USER_GROUP
FROM USERS
WHERE USER_ID = :b1;
-- 8. Group Privilege Check
SELECT *
FROM GROUP_PRIVILEGE
WHERE GROUP_ID = :b1
    AND OBJECT_ID = :b2;
-- 9. Security Settings
SELECT USE_RIGHTS R,
    USE_SECURITY S
FROM SYSTEM_TABLE_SEC;
-- 10. Tests Entry Management
SELECT *
FROM T_TESTS_ENTRY_LINES;
SELECT COUNT(*)
FROM TESTS_ENTRY_LINES T
WHERE T.REG_KEY = :b1
    AND T.TEST_CODE = :b2
    AND T.GROUP_CODE = :b3
    AND T.TEST_TYPE = :b4;
UPDATE TESTS_ENTRY_LINES
SET RESULT = :b1,
    RESULT2 = :b2,
    DESCRIPTIVE = :b3,
    COMMENTS = :b4,
    R_FROM = :b5,
    R_TO = :b6,
    VERIFIED = :b7,
    VERIFIED_BY = :b8,
    UNIT = :b9,
    PROFILE_SER = :b10,
    TEST_STATUS = :b11,
    REPORT_PRINTED = :b12,
    VISIBLE = :b13,
    AGE_COMMENTS = :b14
WHERE REG_KEY = :b15
    AND TEST_CODE = :b16
    AND GROUP_CODE = :b17
    AND TEST_TYPE = :b18;
INSERT INTO TESTS_ENTRY_LINES
SELECT *
FROM T_TESTS_ENTRY_LINES T
WHERE T.REG_KEY = :b1
    AND T.TEST_CODE = :b2
    AND T.GROUP_CODE = :b3
    AND T.TEST_TYPE = :b4;
-- 11. Update Reg Lines (Tests)
UPDATE REG_LINES L
SET TEST_STATUS = 3,
    SEND_RESULT = :b1,
    RECEIVE_RESULT_USER = :b2,
    RECEIVE_DATE = SYSDATE
WHERE (
        L.REG_KEY,
        L.GROUP_CODE,
        L.TEST_CODE,
        L.TEST_TYPE
    ) IN (
        SELECT T.REG_KEY,
            T.GROUP_CODE,
            T.REG_TEST_CODE,
            T.TEST_TYPE
        FROM T_TESTS_ENTRY_LINES T
    );
-- 12. Text Entry Management
DELETE FROM TEXT_ENTRY_LINES T
WHERE (T.REG_KEY, T.GROUP_CODE, TEST_CODE, T.TEST_TYPE) IN (
        SELECT L.REG_KEY,
            L.GROUP_CODE,
            L.TEST_CODE,
            L.TEST_TYPE
        FROM T_TEXT_ENTRY_LINES L
    );
INSERT INTO TEXT_ENTRY_LINES
SELECT *
FROM T_TEXT_ENTRY_LINES;
UPDATE REG_LINES L
SET TEST_STATUS = 3,
    RECEIVE_RESULT_USER = :b1,
    RECEIVE_DATE = SYSDATE
WHERE (
        L.REG_KEY,
        L.GROUP_CODE,
        L.TEST_CODE,
        L.TEST_TYPE
    ) IN (
        SELECT T.REG_KEY,
            T.GROUP_CODE,
            T.REG_TEST_CODE,
            T.TEST_TYPE
        FROM T_TEXT_ENTRY_LINES T
    );
-- 13. Culture Entry Management
DELETE FROM CULTURE_ENTRY_LINES T
WHERE (
        T.REG_KEY,
        T.GROUP_CODE,
        T.CULTURE_CODE,
        T.TEST_TYPE,
        T.ORG_CODE,
        T.ANTI_CODE,
        T.SENSTIVITY_CODE
    ) IN (
        SELECT L.REG_KEY,
            L.GROUP_CODE,
            L.CULTURE_CODE,
            L.TEST_TYPE,
            L.ORG_CODE,
            L.ANTI_CODE,
            L.SENSTIVITY_CODE
        FROM T_CULTURE_ENTRY_LINES L
    );
INSERT INTO CULTURE_ENTRY_LINES
SELECT *
FROM T_CULTURE_ENTRY_LINES T;
UPDATE REG_LINES L
SET TEST_STATUS = 3,
    RECEIVE_RESULT_USER = :b1,
    RECEIVE_DATE = SYSDATE
WHERE (
        L.REG_KEY,
        L.GROUP_CODE,
        L.TEST_CODE,
        L.TEST_TYPE
    ) IN (
        SELECT T.REG_KEY,
            T.GROUP_CODE,
            T.REG_TEST_CODE,
            T.TEST_TYPE
        FROM T_CULTURE_ENTRY_LINES T
    );
-- 14. Registration Counts
SELECT COUNT(REG_KEY)
FROM T_REG;
SELECT COUNT(
        DISTINCT L.GROUP_CODE || L.TEST_CODE || L.TEST_TYPE
    )
FROM T_REG_LINES L;
-- 15. Branch Info
SELECT DISTINCT BRANCH_NAME
FROM BRANCHES,
    REG_LINES L
WHERE BRANCH_CODE = L.SEND_TO_BRANCH;
-- 16. Update Sample Receive Status
UPDATE T_REG_LINES T
SET T.RECEIVE_SAMPLE_USER = :b1,
    T.RE_SAMPLE_DATE = SYSDATE;
-- 17. Cleanup Temp Tables
DELETE FROM T_REG;
DELETE FROM T_REG_LINES;
DELETE FROM T_INSTALLMENT;
DELETE FROM T_PATIENT_PREPARATION;
-- 18. Sample Management
SELECT DISTINCT SEND_SAMPLE
FROM T_REG_LINES;
INSERT INTO INSTALLMENT
SELECT *
FROM T_INSTALLMENT
WHERE (REG_KEY, I_DATE) NOT IN (
        SELECT REG_KEY,
            I_DATE
        FROM INSTALLMENT
    );
INSERT INTO PATIENT_PREPARATION
SELECT *
FROM T_PATIENT_PREPARATION
WHERE (REG_KEY, QUEZ_ID) NOT IN (
        SELECT REG_KEY,
            QUEZ_ID
        FROM PATIENT_PREPARATION
    );
SELECT BRANCH_NAME
FROM BRANCHES
WHERE BRANCH_CODE = (
        SELECT DISTINCT SEND_BY_BRANCH
        FROM T_REG_LINES
    );
-- Identified Program Units / Procedures
-- CHECK_FLASH (Uses TEXT_IO)
-- GET_STATE
-- GET_IMP_STATE
-- BLOCK_UPDATE
-- BLOCK_INSERT
-- BLOCK_DELETE
-- BLOCK_QUERY
-- CENTER_FORM
-- TRANSFER_DATA